// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package log

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SwName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwName) Reset()         { *m = SwName{} }
func (m *SwName) String() string { return proto.CompactTextString(m) }
func (*SwName) ProtoMessage()    {}
func (*SwName) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *SwName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwName.Unmarshal(m, b)
}
func (m *SwName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwName.Marshal(b, m, deterministic)
}
func (m *SwName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwName.Merge(m, src)
}
func (m *SwName) XXX_Size() int {
	return xxx_messageInfo_SwName.Size(m)
}
func (m *SwName) XXX_DiscardUnknown() {
	xxx_messageInfo_SwName.DiscardUnknown(m)
}

var xxx_messageInfo_SwName proto.InternalMessageInfo

func (m *SwName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Switch struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Switch) Reset()         { *m = Switch{} }
func (m *Switch) String() string { return proto.CompactTextString(m) }
func (*Switch) ProtoMessage()    {}
func (*Switch) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *Switch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Switch.Unmarshal(m, b)
}
func (m *Switch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Switch.Marshal(b, m, deterministic)
}
func (m *Switch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Switch.Merge(m, src)
}
func (m *Switch) XXX_Size() int {
	return xxx_messageInfo_Switch.Size(m)
}
func (m *Switch) XXX_DiscardUnknown() {
	xxx_messageInfo_Switch.DiscardUnknown(m)
}

var xxx_messageInfo_Switch proto.InternalMessageInfo

func (m *Switch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Switch) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type Switches struct {
	Switch               []*Switch `protobuf:"bytes,1,rep,name=switch,proto3" json:"switch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Switches) Reset()         { *m = Switches{} }
func (m *Switches) String() string { return proto.CompactTextString(m) }
func (*Switches) ProtoMessage()    {}
func (*Switches) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

func (m *Switches) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Switches.Unmarshal(m, b)
}
func (m *Switches) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Switches.Marshal(b, m, deterministic)
}
func (m *Switches) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Switches.Merge(m, src)
}
func (m *Switches) XXX_Size() int {
	return xxx_messageInfo_Switches.Size(m)
}
func (m *Switches) XXX_DiscardUnknown() {
	xxx_messageInfo_Switches.DiscardUnknown(m)
}

var xxx_messageInfo_Switches proto.InternalMessageInfo

func (m *Switches) GetSwitch() []*Switch {
	if m != nil {
		return m.Switch
	}
	return nil
}

type DHCPLogEntry struct {
	MAC                  string   `protobuf:"bytes,1,opt,name=MAC,proto3" json:"MAC,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DHCPLogEntry) Reset()         { *m = DHCPLogEntry{} }
func (m *DHCPLogEntry) String() string { return proto.CompactTextString(m) }
func (*DHCPLogEntry) ProtoMessage()    {}
func (*DHCPLogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3}
}

func (m *DHCPLogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHCPLogEntry.Unmarshal(m, b)
}
func (m *DHCPLogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHCPLogEntry.Marshal(b, m, deterministic)
}
func (m *DHCPLogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHCPLogEntry.Merge(m, src)
}
func (m *DHCPLogEntry) XXX_Size() int {
	return xxx_messageInfo_DHCPLogEntry.Size(m)
}
func (m *DHCPLogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DHCPLogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DHCPLogEntry proto.InternalMessageInfo

func (m *DHCPLogEntry) GetMAC() string {
	if m != nil {
		return m.MAC
	}
	return ""
}

func (m *DHCPLogEntry) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *DHCPLogEntry) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type SwitchLogEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchLogEntry) Reset()         { *m = SwitchLogEntry{} }
func (m *SwitchLogEntry) String() string { return proto.CompactTextString(m) }
func (*SwitchLogEntry) ProtoMessage()    {}
func (*SwitchLogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{4}
}

func (m *SwitchLogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchLogEntry.Unmarshal(m, b)
}
func (m *SwitchLogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchLogEntry.Marshal(b, m, deterministic)
}
func (m *SwitchLogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchLogEntry.Merge(m, src)
}
func (m *SwitchLogEntry) XXX_Size() int {
	return xxx_messageInfo_SwitchLogEntry.Size(m)
}
func (m *SwitchLogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchLogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchLogEntry proto.InternalMessageInfo

func (m *SwitchLogEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SwitchLogEntry) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SwitchLogEntry) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type DHCPLog struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DHCPLog) Reset()         { *m = DHCPLog{} }
func (m *DHCPLog) String() string { return proto.CompactTextString(m) }
func (*DHCPLog) ProtoMessage()    {}
func (*DHCPLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{5}
}

func (m *DHCPLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHCPLog.Unmarshal(m, b)
}
func (m *DHCPLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHCPLog.Marshal(b, m, deterministic)
}
func (m *DHCPLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHCPLog.Merge(m, src)
}
func (m *DHCPLog) XXX_Size() int {
	return xxx_messageInfo_DHCPLog.Size(m)
}
func (m *DHCPLog) XXX_DiscardUnknown() {
	xxx_messageInfo_DHCPLog.DiscardUnknown(m)
}

var xxx_messageInfo_DHCPLog proto.InternalMessageInfo

func (m *DHCPLog) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DHCPLog) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *DHCPLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DHCPLogs struct {
	Log                  []*DHCPLog `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DHCPLogs) Reset()         { *m = DHCPLogs{} }
func (m *DHCPLogs) String() string { return proto.CompactTextString(m) }
func (*DHCPLogs) ProtoMessage()    {}
func (*DHCPLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{6}
}

func (m *DHCPLogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHCPLogs.Unmarshal(m, b)
}
func (m *DHCPLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHCPLogs.Marshal(b, m, deterministic)
}
func (m *DHCPLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHCPLogs.Merge(m, src)
}
func (m *DHCPLogs) XXX_Size() int {
	return xxx_messageInfo_DHCPLogs.Size(m)
}
func (m *DHCPLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_DHCPLogs.DiscardUnknown(m)
}

var xxx_messageInfo_DHCPLogs proto.InternalMessageInfo

func (m *DHCPLogs) GetLog() []*DHCPLog {
	if m != nil {
		return m.Log
	}
	return nil
}

type SwitchLog struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ts                   string   `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchLog) Reset()         { *m = SwitchLog{} }
func (m *SwitchLog) String() string { return proto.CompactTextString(m) }
func (*SwitchLog) ProtoMessage()    {}
func (*SwitchLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{7}
}

func (m *SwitchLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchLog.Unmarshal(m, b)
}
func (m *SwitchLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchLog.Marshal(b, m, deterministic)
}
func (m *SwitchLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchLog.Merge(m, src)
}
func (m *SwitchLog) XXX_Size() int {
	return xxx_messageInfo_SwitchLog.Size(m)
}
func (m *SwitchLog) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchLog.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchLog proto.InternalMessageInfo

func (m *SwitchLog) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SwitchLog) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SwitchLog) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

func (m *SwitchLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SwitchLogs struct {
	Log                  []*SwitchLog `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SwitchLogs) Reset()         { *m = SwitchLogs{} }
func (m *SwitchLogs) String() string { return proto.CompactTextString(m) }
func (*SwitchLogs) ProtoMessage()    {}
func (*SwitchLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{8}
}

func (m *SwitchLogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchLogs.Unmarshal(m, b)
}
func (m *SwitchLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchLogs.Marshal(b, m, deterministic)
}
func (m *SwitchLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchLogs.Merge(m, src)
}
func (m *SwitchLogs) XXX_Size() int {
	return xxx_messageInfo_SwitchLogs.Size(m)
}
func (m *SwitchLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchLogs.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchLogs proto.InternalMessageInfo

func (m *SwitchLogs) GetLog() []*SwitchLog {
	if m != nil {
		return m.Log
	}
	return nil
}

func init() {
	proto.RegisterType((*SwName)(nil), "log.SwName")
	proto.RegisterType((*Switch)(nil), "log.Switch")
	proto.RegisterType((*Switches)(nil), "log.Switches")
	proto.RegisterType((*DHCPLogEntry)(nil), "log.DHCPLogEntry")
	proto.RegisterType((*SwitchLogEntry)(nil), "log.SwitchLogEntry")
	proto.RegisterType((*DHCPLog)(nil), "log.DHCPLog")
	proto.RegisterType((*DHCPLogs)(nil), "log.DHCPLogs")
	proto.RegisterType((*SwitchLog)(nil), "log.SwitchLog")
	proto.RegisterType((*SwitchLogs)(nil), "log.SwitchLogs")
}

func init() {
	proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886)
}

var fileDescriptor_a153da538f858886 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xd7, 0x76, 0x6c, 0xeb, 0xdb, 0x9c, 0xfa, 0xbc, 0x14, 0x19, 0x32, 0xe2, 0x65, 0x88,
	0x4c, 0x99, 0xe0, 0x5d, 0x36, 0xd9, 0x06, 0x2a, 0x73, 0x3b, 0x79, 0xac, 0x12, 0x6b, 0x60, 0x59,
	0x4a, 0x13, 0x10, 0xff, 0x1e, 0xff, 0x51, 0x49, 0x9a, 0xc4, 0x16, 0x77, 0xf0, 0xf6, 0xfa, 0xbe,
	0xe6, 0xfb, 0x7e, 0x79, 0x2f, 0x10, 0x6f, 0x45, 0x36, 0xce, 0x0b, 0xa1, 0x04, 0x46, 0x5b, 0x91,
	0x91, 0x01, 0xb4, 0x36, 0x9f, 0x4f, 0x29, 0xa7, 0x88, 0xd0, 0xdc, 0xa5, 0x9c, 0x26, 0xc1, 0x30,
	0x18, 0xc5, 0x6b, 0x53, 0x93, 0x4b, 0xad, 0x32, 0xf5, 0xf6, 0xb1, 0x4f, 0xc5, 0x3e, 0x84, 0xcb,
	0x55, 0x12, 0x9a, 0x4e, 0xb8, 0x5c, 0x91, 0x2b, 0xe8, 0x94, 0x7f, 0x53, 0x89, 0xe7, 0xd0, 0x92,
	0xa6, 0x4e, 0x82, 0x61, 0x34, 0xea, 0x4e, 0xba, 0x63, 0x1d, 0x5c, 0xca, 0x6b, 0x2b, 0x91, 0x19,
	0xf4, 0x66, 0x8b, 0xe9, 0xea, 0x41, 0x64, 0xf7, 0x3b, 0x55, 0x7c, 0xe1, 0x11, 0x44, 0x8f, 0x77,
	0x53, 0x9b, 0xa1, 0x4b, 0x1d, 0xfb, 0x5e, 0x08, 0x6e, 0x43, 0x4c, 0xad, 0x63, 0x95, 0x48, 0xa2,
	0x32, 0x56, 0x09, 0xb2, 0x80, 0x7e, 0xe9, 0xeb, 0x7d, 0xf6, 0xc1, 0xfe, 0xc7, 0xe9, 0x19, 0xda,
	0x96, 0x47, 0x4b, 0x2c, 0xb7, 0x06, 0x21, 0xcb, 0x71, 0x00, 0xb1, 0x62, 0x9c, 0x4a, 0x95, 0xf2,
	0xdc, 0x7a, 0xfc, 0x36, 0x30, 0x81, 0x36, 0xa7, 0x52, 0xa6, 0x19, 0xb5, 0x6e, 0xee, 0x93, 0x5c,
	0x40, 0xc7, 0x5a, 0x4a, 0x3c, 0x03, 0x3d, 0x72, 0x3b, 0x90, 0x9e, 0x19, 0x88, 0xd5, 0xd6, 0x66,
	0x17, 0x2f, 0x10, 0xfb, 0x8b, 0xfc, 0x01, 0x70, 0x77, 0x0a, 0xeb, 0x0b, 0x50, 0xd2, 0xf3, 0xcb,
	0x2a, 0x46, 0xb3, 0x8e, 0x31, 0x06, 0xf0, 0xd6, 0x12, 0x87, 0x55, 0x90, 0x7e, 0x65, 0x33, 0x0e,
	0x65, 0xf2, 0x1d, 0x40, 0xa4, 0x29, 0xae, 0x01, 0xe6, 0x54, 0xb9, 0xa1, 0x1c, 0x57, 0x99, 0xcd,
	0xa8, 0x4f, 0x0f, 0xaa, 0x2d, 0x49, 0x1a, 0x38, 0x01, 0x9c, 0x53, 0xb5, 0x61, 0x9c, 0x6d, 0xd3,
	0xc2, 0x3f, 0x07, 0xb7, 0x7e, 0xfd, 0xd2, 0xec, 0x19, 0xa7, 0x91, 0x06, 0xde, 0x42, 0x4f, 0x9f,
	0xf1, 0x77, 0x3f, 0xa9, 0x23, 0x95, 0x49, 0x87, 0xf5, 0xa6, 0x24, 0x8d, 0xd7, 0x96, 0x79, 0xc8,
	0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x64, 0xd7, 0xcf, 0xd5, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogClient interface {
	GetDHCPLog(ctx context.Context, in *DHCPLogEntry, opts ...grpc.CallOption) (*DHCPLogs, error)
	GetSimilarSwitches(ctx context.Context, in *SwName, opts ...grpc.CallOption) (*Switches, error)
	GetSwitchLog(ctx context.Context, in *SwitchLogEntry, opts ...grpc.CallOption) (*SwitchLogs, error)
}

type logClient struct {
	cc grpc.ClientConnInterface
}

func NewLogClient(cc grpc.ClientConnInterface) LogClient {
	return &logClient{cc}
}

func (c *logClient) GetDHCPLog(ctx context.Context, in *DHCPLogEntry, opts ...grpc.CallOption) (*DHCPLogs, error) {
	out := new(DHCPLogs)
	err := c.cc.Invoke(ctx, "/log.Log/GetDHCPLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) GetSimilarSwitches(ctx context.Context, in *SwName, opts ...grpc.CallOption) (*Switches, error) {
	out := new(Switches)
	err := c.cc.Invoke(ctx, "/log.Log/GetSimilarSwitches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) GetSwitchLog(ctx context.Context, in *SwitchLogEntry, opts ...grpc.CallOption) (*SwitchLogs, error) {
	out := new(SwitchLogs)
	err := c.cc.Invoke(ctx, "/log.Log/GetSwitchLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServer is the server API for Log service.
type LogServer interface {
	GetDHCPLog(context.Context, *DHCPLogEntry) (*DHCPLogs, error)
	GetSimilarSwitches(context.Context, *SwName) (*Switches, error)
	GetSwitchLog(context.Context, *SwitchLogEntry) (*SwitchLogs, error)
}

// UnimplementedLogServer can be embedded to have forward compatible implementations.
type UnimplementedLogServer struct {
}

func (*UnimplementedLogServer) GetDHCPLog(ctx context.Context, req *DHCPLogEntry) (*DHCPLogs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDHCPLog not implemented")
}
func (*UnimplementedLogServer) GetSimilarSwitches(ctx context.Context, req *SwName) (*Switches, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimilarSwitches not implemented")
}
func (*UnimplementedLogServer) GetSwitchLog(ctx context.Context, req *SwitchLogEntry) (*SwitchLogs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSwitchLog not implemented")
}

func RegisterLogServer(s *grpc.Server, srv LogServer) {
	s.RegisterService(&_Log_serviceDesc, srv)
}

func _Log_GetDHCPLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHCPLogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).GetDHCPLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.Log/GetDHCPLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).GetDHCPLog(ctx, req.(*DHCPLogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_GetSimilarSwitches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).GetSimilarSwitches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.Log/GetSimilarSwitches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).GetSimilarSwitches(ctx, req.(*SwName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_GetSwitchLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchLogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).GetSwitchLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.Log/GetSwitchLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).GetSwitchLog(ctx, req.(*SwitchLogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

var _Log_serviceDesc = grpc.ServiceDesc{
	ServiceName: "log.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDHCPLog",
			Handler:    _Log_GetDHCPLog_Handler,
		},
		{
			MethodName: "GetSimilarSwitches",
			Handler:    _Log_GetSimilarSwitches_Handler,
		},
		{
			MethodName: "GetSwitchLog",
			Handler:    _Log_GetSwitchLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}
